### PR TITLE
Change docker base image

### LINKED ISSUE #47: Docker base image
Semagrow docker uses `tomcat:8.5-jre8-alpine` as its base image. Alpine uses `musl` and we should test its performance in comparison with `glibc` based images such as `tomcat/8.5-jre8-slim` which is bigger (alpine 106MB, slim 223MB) but maybe outperforms Alpine. Performance is more important for semagrow than disk space used especially if the difference is in MBs.

### PR DESCRIPTION
**Pull request by gmouchakis**
Change docker base image to tomcat:8.5-jre8-slim.

Closes #47

### CODE REVIEW

**Comment by gmouchakis** [comment]
@antru6 kobe benchmark could be used to compare tomcat:8.5-jre8-alpine vs tomcat/8.5-jre8-slim.

**Comment by stasinos** [comment]
I am re-visiting PRs as we are preparing for a release. Could it be that an even newer base image would be preferable?

**Comment by gmouchakis** [comment]
Tomcat 8 is no longer supported[1] so I suppose we should update the base image to at least tomcat 9 or even better tomcat 10. Java 8 is still supported in these versions[2].

[1] http://tomcat.apache.org/tomcat-80-eol.html
[2] http://tomcat.apache.org/whichversion.html

**Comment by gmouchakis** [comment]
I've just realized that tomcat 8.0 is not supported any more but our base image, tomcat 8.5, is still supported.

**Pull request merged**
