### PR TITLE
GeoSPARQL support

### PR DESCRIPTION
**Pull request by stasinos**
The work in the devel-xearth branch has advanced support for federations mixing GeoSPARQL and SPARQL stores and support for detailed KOBE metrics. This release also includes various features and fixes, both at the methodological and at the implementation level.

Updates in source selection:

    Implementation of a new source selector that filters-out non-joinable sources, based on the URI prefixes of the shared variables (cf. #60, #75, #76)
    Preliminary version of a geospatial source selection that handles only specific types of geospatial filters (cf. #44), to be re-visited to handle more cases

Updates in query planning:

    Planning of complex queries (cf. #63, #77)
    Filter pushdowns into the sources (cf. #44, #63)
    Fixes in selectivity and cardinality estimator (cf. #63, #79)

Updates in query execution:

    Extending query execution with geospatial (GeoSPARQL and stSPARQL) functions (cf. #36)
    Fix in query execution configuration (cf. #46)
    Fix redundant language tags in sparql rendering of query executor (cf. #78)

Other updates:

    Modify log messages for integration with KOBE (cf. #52, #74)
    Dockerfile updates (cf. #43, #62)
    Updates in packages (cf. #40, #42)
    Minor frontend updates (cf. #39)
    Integration with Glassfish 4 (cf. #38)

### CODE REVIEW

**Comment by stasinos** [comment]
@antru6 @acharal @gmouchakis Any other comments about the features in v2.1.0?

**Comment by acharal** [comment]
Is this going to be squashed to master? 
Some of the commits seems independent to the geosparql feature, eg. b503a9e.

**Comment by stasinos** [comment]
I was planning to merge-commit, too much history to squash.

**Comment by antru6** [comment]
I have prepared a more detailed text with the updates of this new release, if you want to include it in the PR text:

Updates in source selection:
* Implementation of a new source selector that filters-out non-joinable sources, based on the URI prefixes of the shared variables (cf. #60, #75, #76)
* Preliminary version of a geospatial source selection that handles only specific types of geospatial filters (cf. #44)

Updates in query planning:
* Planning of complex queries (cf. #63, #77)
* Filter pushdowns into the sources (cf. #44, #63)
* Fixes in selectivity and cardinality estimator (cf. #63, #79)

Updates in query execution:
* Extending query execution with geospatial (GeoSPARQL and stRDF) functions (cf. #36)
* Fix in query execution configuration (cf. #46)
* Fix redundant language tags in sparql rendering of query executor (cf. #78)

Other updates:
* Modify log messages for integration with KOBE (cf. #52, #72, #74)
* Dockerfile updates (cf. #43, #62)
* Updates in packages (cf. #40, #42)
* Minor frontend updates (cf. #39)
* Integration with Glassfish 4 (cf. #38)

**Comment by stasinos** [comment]
Nice, thx!

**Pull request merged**
