### PR TITLE
URI Prefix-based Query-Aware Source Selector

### PR DESCRIPTION
**Pull request by antru6**
Implementation of a new source selector that filters-out non-joinable sources, based on the URI prefixes of the shared variables.

### CODE REVIEW

**Comment by stasinos** [comment]
Does this replace the previous functionality, or are both accessible through configuration options?

**Comment by antru6** [comment]
This new source selector wraps the previous ones. That is, the PrefixQueryAwareSourceSelector wraps the CachedSourceSelector (which caches the results of the ASK queries of the AskSourceSelector), which wraps the AskSourceSelector and so on. Since this new selector is based on a pruning strategy, if the metadata file does not contain any information about the prefixes, the new selector would have no effect on the sources list obtained by the inner selectors.

**Comment by stasinos** [comment]
Thank you for this explanation.

Please also explain how the previous behaviour can be recovered, either at compile time or at run time.

**Comment by antru6** [comment]
Unfortunately, the previous functionality cannot be recovered with a configuration option or a compile options (as in the other selectors), but it can be easily removed by removing two lines in the SailFactory in the method which initializes the source selectors (cf. [https://github.com/semagrow/semagrow/commit/832a76f57dc2ed650158a6a62bec735e063827e1#diff-553ef8b60a453dfbd2ef6bd58f6c3adeR132](url))

**Pull request merged**
